# Generated by Django 2.2.10 on 2021-04-20 14:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Options',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option_options', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OptionUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('optionuser_id', models.IntegerField()),
                ('optionuser_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll_name', models.CharField(max_length=50)),
                ('poll_desc', models.TextField()),
                ('poll_start', models.DateTimeField(auto_now_add=True)),
                ('poll_finish', models.DateTimeField()),
                ('poll_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersOptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_option_options', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Options')),
                ('user_option_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.OptionUser')),
            ],
        ),
        migrations.AddField(
            model_name='options',
            name='option_poll',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Poll'),
        ),
    ]
